# 기본 앱 설정
spring.application.name=pki
server.port=8080

# MySQL DB 설정
spring.datasource.url=jdbc:mysql://localhost:3306/project1?serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# PortOne API 설정
portone.public.store-id=${PORTONE_PUBLIC_STORE_ID}
portone.public.channel-key=${PORTONE_PUBLIC_CHANNEL_KEY}
portone.api-secret=${PORTONE_API_SECRET}
portone.api.base-url=https://api.portone.io

# JPA 설정
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# PKI Server Secret
pki.server-secret=ANTIGRAVITY_SECRET_KEY

# Spring Boot 3/4 경로 매칭 전략
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
