package com.Nbbang.backend.domain.product.entity;

import java.util.Arrays;

public enum ProductCategory {
    MECHANICAL_ENGINEERING,
    FIRE_SAFETY,
    ELECTRICAL_ENGINEERING,
    ELECTRONICS_ENGINEERING,
    COMPUTER_SOFTWARE,
    COMPUTER_INFORMATION_COMMUNICATION,
    GAME_CONTENTS,
    ARTIFICIAL_INTELLIGENCE,
    INDUSTRIAL_DESIGN,
    VISUAL_DESIGN,
    FASHION_DESIGN,
    INTERIOR_ARCHITECTURE,
    ADVERTISING_MEDIA,
    BROADCAST_VIDEO,
    ANIMATION_WEBTOON,
    BROADCAST_CREATIVE_WRITING,
    BROADCAST_ENTERTAINMENT,
    FOOD_NUTRITION,
    HEALTHCARE_ADMINISTRATION,
    OCCUPATIONAL_THERAPY,
    ANIMAL_HEALTH,
    EMERGENCY_MEDICAL_SERVICES,
    DENTAL_HYGIENE,
    YUHAN_BIOPHARMACEUTICAL,
    YUHAN_BIOCHEMICAL,
    SKIN_MAKEUP,
    BEAUTY_COSMETICS,
    SOCIAL_WELFARE,
    SPORTS_REHABILITATION,
    PET_INDUSTRY,
    HOTEL_CULINARY,
    CAFE_BAKERY,
    HOTEL_TOURISM,
    AVIATION_SERVICE,
    JAPANESE_BUSINESS,
    MANAGEMENT_INFORMATION,
    TAX_ACCOUNTING,
    FREE_MAJOR,
    GENERAL;

    public static boolean supports(String value) {
        return Arrays.stream(values()).anyMatch(category -> category.name().equals(value));
    }
}
