/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#8300b4",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#f0c1ff",
        "primary": "#006a71",
        "surface-container": "#f8f8f8",
        "surface-bright": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#001d35",
        "inverse-surface": "#1a1a1a",
        "on-surface-variant": "#444747",
        "surface-container-highest": "#e0e0e0",
        "surface-dim": "#f0f0f0",
        "tertiary-dim": "#0061a4",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#f5f5f5",
        "error-dim": "#ba1a1a",
        "on-tertiary-fixed": "#001d35",
        "tertiary": "#0061a4",
        "outline": "#707878",
        "secondary-dim": "#8300b4",
        "tertiary-container": "#d1e4ff",
        "on-primary": "#ffffff",
        "on-error-container": "#410002",
        "surface-container-high": "#eeeeee",
        "outline-variant": "#bfc8c8",
        "secondary-fixed": "#f0c1ff",
        "tertiary-fixed-dim": "#a1c9ff",
        "error": "#ba1a1a",
        "inverse-primary": "#4fe0eb",
        "primary-fixed": "#97f0ff",
        "surface-variant": "#dae4e4",
        "on-primary-fixed": "#002022",
        "on-background": "#1a1a1a",
        "secondary": "#8300b4",
        "on-primary-container": "#002022",
        "surface": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004f55",
        "background": "#ffffff",
        "secondary-container": "#ffd6ff",
        "on-secondary-container": "#2c0040",
        "surface-tint": "#006a71",
        "on-tertiary-fixed-variant": "#00497d",
        "primary-dim": "#006a71",
        "primary-fixed-dim": "#4fe0eb",
        "tertiary-fixed": "#d1e4ff",
        "on-secondary-fixed": "#2c0040",
        "primary-container": "#97f0ff",
        "on-surface": "#1a1a1a",
        "surface-container-low": "#f5f5f5",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ["Space Grotesk", "Noto Sans KR", "sans-serif"],
        body: ["Manrope", "Noto Sans KR", "sans-serif"],
        label: ["Manrope", "Noto Sans KR", "sans-serif"]
      }
    },
  },
  plugins: [],
}
